import type {
  DuesProofApprovalView,
  JoinRequestApprovalView,
  ProposalApprovalView,
} from "@/lib/approvals/types";

export const MOCK_ADMIN_PROPOSALS: ProposalApprovalView[] = [
  {
    id: "proposal-1",
    title: "Google Cloud and Generative AI Buildathon",
    club_id: "nile-google-developers",
    club_name: "Nile Google Developers",
    submitted_by_id: "president-1",
    submitted_by_name: "Farouk Aliyu",
    proposed_date: "2026-09-12",
    venue: "Technology Auditorium",
    budget: 150000,
    description: "A practical buildathon for student teams working with responsible AI tools.",
    aim_objectives: null,
    proposed_activity: null,
    advisor_name: "Dr. Aliyu Bello",
    advisor_remarks: "I have reviewed the academic timeline and safety protocols for this proposal. Highly recommended for Directorate clearance.",
    admin_remarks: null,
    status: "pending_admin_review",
    submitted_at: "2026-08-10T10:00:00.000Z",
    approval_history: [],
    can_authorize: true,
    can_override: false,
  },
  {
    id: "proposal-2",
    title: "Inter-Faculty Debate Finals",
    club_id: "nile-debate-club",
    club_name: "Nile Debate Club",
    submitted_by_id: "president-2",
    submitted_by_name: "Tariq Ibrahim",
    proposed_date: "2026-09-20",
    venue: "Main Auditorium",
    budget: 85000,
    description: "The final round of the university's inter-faculty debate series.",
    aim_objectives: null,
    proposed_activity: null,
    advisor_name: "Prof. Halima Yusuf",
    advisor_remarks: "I have reviewed the academic timeline and safety protocols for this proposal. Highly recommended for Directorate clearance.",
    admin_remarks: null,
    status: "pending_admin_review",
    submitted_at: "2026-08-12T10:00:00.000Z",
    approval_history: [],
    can_authorize: true,
    can_override: false,
  },
];

export const MOCK_JOIN_REQUESTS: JoinRequestApprovalView[] = [
  {
    id: "join-1",
    profile_id: "student-join-1",
    student_id: "NIL/2023/UG/0491",
    student_name: "Ibrahim Sani",
    student_email: "ibrahim.sani@nileuniversity.edu.ng",
    club_id: "nile-climate-initiatives-club",
    club_name: "Nile Climate Initiatives Club",
    club_available: true,
    statement: "I want to support practical sustainability projects on campus.",
    applied_at: "2026-08-18T14:30:00Z",
    status: "pending",
    dues_status: "submitted",
    dues_amount: 10000,
    whatsapp_onboarding_status: "not_ready",
    whatsapp_added: false,
    whatsapp_ready: false,
    whatsapp_chat_url: null,
    profile_removed: false,
  },
];

export const MOCK_DUES_PROOFS: DuesProofApprovalView[] = [
  {
    id: "proof-1",
    student_id: "NIL/2024/UG/1029",
    student_name: "Fatima Aliyu",
    student_email: "fatima.aliyu@nileuniversity.edu.ng",
    club_id: "nile-business-club",
    club_name: "Nile Business Club",
    amount: 10000,
    payment_channel: "Bank transfer",
    reference_number: "REF-NUB-984210",
    proof_document_url: "/oneclub.svg",
    has_proof: true,
    status: "submitted",
    created_at: "2026-08-18T16:15:00Z",
    payer_note: null,
  },
];
