import type { AdminFeedbackView } from "./types";

export function mockAdminFeedback(): AdminFeedbackView[] {
  return [
    {
      id: "fb-101",
      category: "dues",
      title: "Bank-transfer proof review time for session dues",
      message:
        "Can bank transfer verifications for Nile Google Developers Club dues be reviewed before Friday? Several students want to participate in the upcoming AI workshop and need active member status.",
      authorName: "Tariq Ibrahim",
      authorRole: "student",
      studentId: "210103044",
      clubName: "Nile Google Developers",
      submittedAt: "2026-08-18T11:20:00Z",
      rating: 4,
      status: "open",
      identityAvailable: true,
    },
    {
      id: "fb-102",
      category: "club",
      title: "Inter-club collaboration proposal guidelines",
      message:
        "Having a standardized format or joint proposal template for co-hosted initiatives between TEDx Nile and Nile Business Club would streamline approval workflows between faculty advisors.",
      authorName: "Zainab Bello",
      authorRole: "executive",
      studentId: "200104012",
      clubName: "Nile Business Club",
      submittedAt: "2026-08-17T14:45:00Z",
      rating: 5,
      status: "open",
      identityAvailable: true,
    },
    {
      id: "fb-103",
      category: "joining",
      title: "Clearer notification when membership application is accepted",
      message:
        "When my membership application for Nile Cyber Security Club was reviewed, it would be helpful to receive an SMS or direct push alert in addition to the in-app notice.",
      authorName: "Emeka Okafor",
      authorRole: "student",
      studentId: "220105088",
      clubName: "Cyber Security Club",
      submittedAt: "2026-08-16T16:10:00Z",
      rating: 4,
      status: "open",
      identityAvailable: true,
    },
    {
      id: "fb-104",
      category: "onboarding",
      title: "New executive handbook and proposal orientation",
      message:
        "As a newly elected executive for Nile Robotics Society, a 15-minute digital walkthrough on grant budgeting and venue protocol in OneClub would make the onboarding process even smoother.",
      authorName: "Farida Al-Mansur",
      authorRole: "executive",
      studentId: "210102003",
      clubName: "Nile Robotics Society",
      submittedAt: "2026-08-15T09:30:00Z",
      rating: 4,
      status: "open",
      identityAvailable: true,
    },
    {
      id: "fb-105",
      category: "login_access",
      title: "Single Sign-On login session persistence on mobile devices",
      message:
        "When switching between Nile University student portal tabs on iOS Safari, the Campus One institutional login occasionally prompts for 2FA re-verification.",
      authorName: "Oluwaseun Adeleke",
      authorRole: "student",
      studentId: "220108031",
      submittedAt: "2026-08-14T10:15:00Z",
      rating: 3,
      status: "open",
      identityAvailable: true,
    },
    {
      id: "fb-106",
      category: "general",
      title: "OneClub interface accessibility and night study mode",
      message:
        "The dark mode theme is very comfortable during late-night library study sessions. Appreciate the high-contrast typography and clean spacing across the platform.",
      authorName: "Fatima Kabir",
      authorRole: "student",
      studentId: "230101019",
      submittedAt: "2026-08-12T19:00:00Z",
      rating: 5,
      status: "open",
      identityAvailable: true,
    },
    {
      id: "fb-107",
      category: "club",
      title: "Equipment storage coordination between student societies",
      message:
        "Can Club Services provide a shared schedule for audio-visual equipment checkouts in the student center? This will prevent double-booking between societies.",
      authorName: "Mustapha Garba",
      authorRole: "president",
      studentId: "190101004",
      clubName: "Nile Literary Society",
      submittedAt: "2026-08-10T13:20:00Z",
      rating: 4,
      status: "open",
      identityAvailable: true,
    },
  ];
}
